# curl -X 'POST'
#  'http://127.0.0.1:8095/api/auth/register'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "username": "admin",
#  "password": "admin"
#}'
POST http://127.0.0.1:8095/api/auth/register
accept: */*
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

# curl -X 'POST'
#  'http://127.0.0.1:8095/api/auth/login'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "username": "admin",
#  "password": "admin"
#}'
POST http://127.0.0.1:8095/api/auth/login
accept: */*
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###


POST http://127.0.0.1:8095/api/auth/register
accept: */*
Content-Type: application/json

{
  "username": "string",
  "password": "string"
}

###

POST http://127.0.0.1:8095/api/v1/commands/transaction
accept: */*
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTAwMDY5NywiZXhwIjoxNzQ1MDM2Njk3fQ.mIc3-ALDasLCBiFaDx2pKzEWCOWAENSuMnUYgzmK2Y0

{
  "reference": "string",
  "amount": 0
}

###

POST http://127.0.0.1:8095/api/auth/request-code
accept: */*
Content-Type: application/json

{
  "username": "papacoundia@gmail.com",
  "email": "papacoundia@gmail.com"
}

###
POST http://127.0.0.1:8095/api/auth/check-code
accept: */*
Content-Type: application/json

{
  "username": "papacoundia@gmail.com",
  "email": "papacoundia@gmail.com",
  "code": "4550"
}

###